language: python
python:
- "3.7"

before_install:

install: 
- pip install .
- pip install coverage
- pip install nose coverage
- pip install coveralls

script:  
- nosetests --with-coverage

after_success:
  coveralls 