language: python
python:
- "3.4"

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

install: 
- pip install .
- pip install coverage
- pip install nose coverage
- pip install coveralls

script:  
- python setup.py nosetests --with-coverage --cover-package pypiview
- nosetests --with-coverage

after_success:
  coveralls 